### ISSUE TITLE
missign do "not disturb" button

### ISSUE THREAD

**Issue by radical4ever** [pawelswiszcz/Avatar-Gnome-Shell-Extension#24]
hi, i like this extension a lot but the icon used for the do not disturb button is missing, i know it from the gnome-shell theme but is it possible to override this and put a custom one. thank you
![Captura desde 2022-07-22 15-09-29](https://user-images.githubusercontent.com/83252104/180498706-d5adf598-cd40-4240-9153-10dfff990d9c.png)

**Comment by pawelswiszcz** [comment]
Hello @Radical4ever 
Thanks for using the Avatar Gnome shell extension. 
> but is it possible to override this and put a custom one

Yes, it is possible. I'll add this custom icon name soon. But probably in more than two or three weeks, because of the summertime. For now please use another icon theme that has this icon for example I'm using this icon theme `Tela-manjaro-dark` and icon path is  `/usr/share/icons/Tela-manjaro-dark/symbolic/status/notifications-symbolic.svg`

**Comment by pawelswiszcz** [comment]
@Radical4ever fixed in version 18
The icon style can be changeable in the preferences window. Please check after update

**Comment by radical4ever** [comment]
@pawelswiszcz Works like a charm!. i used this one `preferences-system-notifications-symbolic`
![image](https://user-images.githubusercontent.com/83252104/183255732-8441f861-a2bd-4ab9-9f23-06dc6660d211.png)
thank you for the fix!!!
